import React from 'react'
import { describe, it, expect, vi, beforeEach } from 'vitest'
import { render, screen, fireEvent, waitFor } from '@testing-library/react'
import { BrowserRouter } from 'react-router-dom'
import { AuthContext } from '../context/AuthContext'
import Chat from './Chat'
import { API_BASE_URL } from '../config'

const SESSIONS_URL = `${API_BASE_URL}/api/chat/sessions`
const CHAT_URL = `${API_BASE_URL}/api/chat`

const mockAuth = {
  auth: { token: 'test-token', email: 'testuser@example.com' },
  isAuthenticated: true
}

const renderWithAuth = (component) => {
  return render(
    <BrowserRouter>
      <AuthContext.Provider value={mockAuth}>
        {component}
      </AuthContext.Provider>
    </BrowserRouter>
  )
}

describe('Chat Component', () => {
  beforeEach(() => {
    vi.restoreAllMocks()
    // Default mock handles the sessions fetch that fires on every mount
    global.fetch = vi.fn((url) => {
      if (url === SESSIONS_URL) {
        return Promise.resolve({ ok: true, json: () => Promise.resolve([]) })
      }
      return Promise.resolve({ ok: false, status: 500, json: () => Promise.resolve({}) })
    })
  })

  it('renders chat interface with input and button', () => {
    renderWithAuth(<Chat />)

    expect(screen.getByText('AI Chat')).toBeInTheDocument()
    expect(screen.getByPlaceholderText('Ask anything...')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /ask/i })).toBeInTheDocument()
  })

  it('does not repeat the Gemini attribution across a separate subtitle and the ask box caption', () => {
    renderWithAuth(<Chat />)

    expect(screen.queryByText('Powered by Google Gemini')).not.toBeInTheDocument()
    expect(screen.getByText('Responses are AI-generated by Google Gemini.')).toBeInTheDocument()
  })

  it('renders sidebar with new chat button', () => {
    renderWithAuth(<Chat />)
    expect(screen.getByText('+ New Chat')).toBeInTheDocument()
  })

  it('fetches sessions on mount and displays them in sidebar', async () => {
    global.fetch = vi.fn((url) => {
      if (url === SESSIONS_URL) {
        return Promise.resolve({
          ok: true,
          json: () => Promise.resolve([{ id: 1, title: 'Old convo', createdAt: '2024-01-01T00:00:00' }])
        })
      }
      return Promise.resolve({ ok: true, json: () => Promise.resolve({}) })
    })

    renderWithAuth(<Chat />)

    await waitFor(() => {
      expect(screen.getByText('Old convo')).toBeInTheDocument()
    })
  })

  it('displays empty state message when no messages', () => {
    renderWithAuth(<Chat />)

    expect(screen.getByText('No messages yet — ask below.')).toBeInTheDocument()
  })

  it('sends message and displays it in chat history', async () => {
    global.fetch = vi.fn((url) => {
      if (url === SESSIONS_URL) {
        return Promise.resolve({ ok: true, json: () => Promise.resolve([]) })
      }
      return Promise.resolve({
        status: 200,
        json: () => Promise.resolve({ response: 'AI response', model: 'gemini-2.0-flash', sessionId: 1, sessionTitle: 'Test' })
      })
    })

    renderWithAuth(<Chat />)

    const input = screen.getByPlaceholderText('Ask anything...')
    const sendButton = screen.getByRole('button', { name: /ask/i })

    fireEvent.change(input, { target: { value: 'Hello AI' } })
    fireEvent.click(sendButton)

    await waitFor(() => {
      expect(screen.getByText('Hello AI')).toBeInTheDocument()
    })
  })

  it('calls API with correct message, sessionId, and authorization header', async () => {
    const fetchMock = vi.fn((url, options) => {
      if (url === SESSIONS_URL) {
        return Promise.resolve({ ok: true, json: () => Promise.resolve([]) })
      }
      return Promise.resolve({
        status: 200,
        json: () => Promise.resolve({ response: 'Test response', model: 'gemini-2.0-flash', sessionId: 1, sessionTitle: 'Test message' })
      })
    })
    global.fetch = fetchMock

    renderWithAuth(<Chat />)

    const input = screen.getByPlaceholderText('Ask anything...')
    const sendButton = screen.getByRole('button', { name: /ask/i })

    fireEvent.change(input, { target: { value: 'Test message' } })
    fireEvent.click(sendButton)

    await waitFor(() => {
      expect(fetchMock).toHaveBeenCalledWith(
        CHAT_URL,
        expect.objectContaining({
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer test-token'
          },
          // sessionId is null because no session is active when the first message is sent
          body: JSON.stringify({ message: 'Test message', sessionId: null })
        })
      )
    })
  })

  it('displays AI response after receiving it', async () => {
    global.fetch = vi.fn((url) => {
      if (url === SESSIONS_URL) {
        return Promise.resolve({ ok: true, json: () => Promise.resolve([]) })
      }
      return Promise.resolve({
        status: 200,
        json: () => Promise.resolve({ response: 'AI says hello!', model: 'gemini-2.0-flash', sessionId: 1, sessionTitle: 'Test' })
      })
    })

    renderWithAuth(<Chat />)

    const input = screen.getByPlaceholderText('Ask anything...')
    const sendButton = screen.getByRole('button', { name: /ask/i })

    fireEvent.change(input, { target: { value: 'Hello' } })
    fireEvent.click(sendButton)

    await waitFor(() => {
      expect(screen.getByText('AI says hello!')).toBeInTheDocument()
    })
  })

  it('displays error message when API fails', async () => {
    global.fetch = vi.fn((url) => {
      if (url === SESSIONS_URL) {
        return Promise.resolve({ ok: true, json: () => Promise.resolve([]) })
      }
      return Promise.resolve({
        status: 500,
        json: () => Promise.resolve({ error: 'Server error' })
      })
    })

    renderWithAuth(<Chat />)

    const input = screen.getByPlaceholderText('Ask anything...')
    const sendButton = screen.getByRole('button', { name: /ask/i })

    fireEvent.change(input, { target: { value: 'Hello' } })
    fireEvent.click(sendButton)

    await waitFor(() => {
      expect(screen.getByText('Server error')).toBeInTheDocument()
    })
  })

  it('shows loading state while waiting for response', async () => {
    global.fetch = vi.fn((url) => {
      if (url === SESSIONS_URL) {
        return Promise.resolve({ ok: true, json: () => Promise.resolve([]) })
      }
      return new Promise((resolve) => {
        setTimeout(() => {
          resolve({
            status: 200,
            json: () => Promise.resolve({ response: 'Delayed response', model: 'gemini-2.0-flash', sessionId: 1, sessionTitle: 'Test' })
          })
        }, 100)
      })
    })

    renderWithAuth(<Chat />)

    const input = screen.getByPlaceholderText('Ask anything...')
    const sendButton = screen.getByRole('button', { name: /ask/i })

    fireEvent.change(input, { target: { value: 'Hello' } })
    fireEvent.click(sendButton)

    expect(screen.getByRole('button', { name: /sending/i })).toBeInTheDocument()
    expect(screen.getByText(/thinking/i)).toBeInTheDocument()
  })

  it('disables send button when input is empty', () => {
    renderWithAuth(<Chat />)

    const sendButton = screen.getByRole('button', { name: /ask/i })
    expect(sendButton).toBeDisabled()
  })

  it('appends no second user message and does not clear the input a second time when submitted twice while a send is in flight', async () => {
    let resolveChat
    global.fetch = vi.fn((url) => {
      if (url === SESSIONS_URL) {
        return Promise.resolve({ ok: true, json: () => Promise.resolve([]) })
      }
      return new Promise((resolve) => { resolveChat = resolve })
    })

    renderWithAuth(<Chat />)

    const input = screen.getByPlaceholderText('Ask anything...')
    const form = input.closest('form')

    fireEvent.change(input, { target: { value: 'First message' } })
    fireEvent.submit(form)

    // First submit's synchronous work (optimistic append + input clear) has
    // run; the fetch itself is still unresolved, so isSending is true and
    // the input is disabled. Typing again and submitting again is the
    // ordering hazard: without the guard sitting above the optimistic
    // append, this would push a ghost second user message and re-clear
    // whatever's in the box.
    fireEvent.change(input, { target: { value: 'Second message' } })
    fireEvent.submit(form)

    // Guarded call is dropped synchronously, so no need to waitFor: neither
    // a second user message nor a cleared input should ever appear.
    expect(screen.queryByText('Second message')).not.toBeInTheDocument()
    expect(input).toHaveValue('Second message')

    resolveChat({
      status: 200,
      json: () => Promise.resolve({ response: 'AI reply', model: 'gemini-2.0-flash', sessionId: 1, sessionTitle: 'Test' })
    })

    await waitFor(() => {
      expect(screen.getByText('AI reply')).toBeInTheDocument()
    })
    // Still exactly one user message after the response lands, and the
    // second typed-but-blocked message never got sent or appended.
    expect(screen.getAllByText('First message')).toHaveLength(1)
    expect(screen.queryByText('Second message')).not.toBeInTheDocument()
  })
})
